### ISSUE TITLE
Change output format

### ISSUE THREAD

**Issue by TG1999** [nexB/python-inspector#68]
// First design - use file like as an input in sctk, resolved_packages for metadata
```
packages: // list of metadata like python-inspector
resolved_dependencies_graph: // resolution
files:
    -   path: requirements.txt
        type: file
        package_data:
            -   type: pypi
            -   dependencies: []
```
// Second Design - no file sections
```
resolved_packages: // list of metadata like python-inspector
resolved_dependencies_graph: // resolution
primary_packages:
    -   type: pypi
        dependencies: [] // requirements in python-inspector
        from_path: requirements.txt
        namespace:
        name: scancode-toolkit
        version: 31.1.1
        qualifiers: {}
        subpath:
        primary_language: Python
        description:
        release_date:
        parties:
            -   type: person
                role: author
                name: nexB. Inc. and others
                email: info@aboutcode.org
                url:
        keywords: []
        homepage_url: https://github.com/nexB/scancode-toolkit
        download_url:
        size:
        sha1:
        md5:
        sha256:
        sha512:
        bug_tracking_url:
        code_view_url:
        vcs_url:
        copyright:
        license_expression:
        declared_license:
        notice_text:
        source_packages: []
        file_references: []
        extra_data: {}
```
